version: "3.8"

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tbd
      POSTGRES_DB: mockpfi
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 1s
      retries: 5

  pfi-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "9000:9000"
    environment:
      NODE_ENV: production
      ENV: production
      LOG_LEVEL: info
      HOST: localhost
      PORT: 9000
      SEC_DB_HOST: postgresdb
      SEC_DB_PORT: 5432
      SEC_DB_USER: postgres
      SEC_DB_PASSWORD: tbd
      SEC_DB_NAME: mockpfi
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
      - shared-data:/home/node/app/javascript/tbdex-pfi-exemplar/shared

  kotlin-service:
    build:
      context: .
      dockerfile: Dockerfile.kotlin
    ports:
      - "8080:8080"
    depends_on:
      - pfi-app
    volumes:
      - shared-data:/app/shared

volumes:
  shared-data: