/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import tbdex.sdk.web5.Jwk
import tbdex.sdk.web5.InMemoryKeyManager

import tbdex.sdk.web5.BearerDid
import java.io.File

class App {
    val greeting: String
        get() {
            return "Starting kt..."
        }
}

fun main() {
    println(App().greeting)

    println("Hello from Kotlin service!")

    val sharedDir = "/app/shared"
    val fileNames = listOf("issuerDid.txt", "pfiDid.txt", "signedCredential.txt")

    fileNames.forEach { fileName ->
        val file = File("$sharedDir/$fileName")
        if (file.exists()) {
            println("Contents of $fileName:")
            println(file.readText())
            println("--------------------")
        } else {
            println("$fileName not found.")
        }
    }

    val pfiDidUri = "did:dht:swit41ctrddy1s38c5j46yfgbxmwo1emau71zo5hn1tws1g63hiy"
    val didUri = "did:dht:1fs5hnxsgtxgdr4wzqi38cnj46b1whhn94ojwo66g8hsc5bt3fgy"

    val keyManager = InMemoryKeyManager(listOf())
    val publicJwk = keyManager.importPrivateJwk(Jwk(
        "EdDSA",
        "OKP",
        "Ed25519",
        "jVOdpSIN-DhddW_XVnDipukuzu6-8zieXQtkECZYJ04",
        "kW2-CfY0XmGTVLurk7BJ14Mqc4L-oJpD3jH5ZmwxyUw",
        null
    ))
    val bearerDid = BearerDid(didUri, keyManager)

    println("Bearer Did: $bearerDid")
    println("~~~Finished~~~")
}
